
[build]
  command = "npm run build"
  publish = "dist"

[functions]
  directory = "netlify/functions"

[build.environment]
  NODE_VERSION = "20"

# SPA: redirige todo a index.html
[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200
