
[build]
  base = "bitacora-actividades-app"   # <-- tu subcarpeta con package.json
  command = "npm run build"
  publish = "dist"

[functions]
  directory = "netlify/functions"     # <-- relativo a esa base. Mueve las functions dentro de la base.

[build.environment]
  NODE_VERSION = "20"

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200
